version: 2


sources:
 - name: hubspot_raw
   database: HUBSPOT_DB
   schema: RAW
   tables:
     - name: LISTINGS_RAW
     - name: CALENDAR_RAW
     - name: GENERATED_REVIEWS_RAW
     - name: AMENITIES_CHANGELOG_RAW


models:
 - name: stg_listings
   description: "Staging model: cleans and types LISTINGS_RAW for downstream modeling."
   columns:
     - name: listing_id
       description: "Canonical listing id (int)."
       tests: 
       - not_null 
       - unique
     - name: listing_name
       description: "Listing title."
       tests: 
       - not_null
     - name: list_price
       description: "Numeric price (cleaned from $/commas)."

 - name: stg_calendar
   description: "Staging model for calendar: one row per listing-date with typed fields."
   columns:
    - name: listing_id
      description: "Cleaned listing id (integer)"
      tests:
      - not_null
    - name: date
      description: "Calendar date"
      tests:
        - not_null
    - name: available
      description: "Normalized boolean availability"
    - name: price
      description: "Nightly price as numeric"

 - name: stg_reviews
   description: "Staging model for generated reviews (clean date, numeric score, ids)."
   columns:
      - name: review_id
        description: "Cleaned numeric review id (PK)."
        tests:
          - not_null
          - unique

      - name: listing_id
        description: "FK to listings (cleaned)."
        tests:
          - not_null

      - name: review_date
        description: "Date of the review."
        tests:
          - not_null

      - name: review_score
        description: "Numeric review score (nullable if malformed)."

 - name: stg_amenities_changelog
   description: "Staging model that standardizes the amenities changelog events."
   columns:
      - name: listing_id
        description: "Unique listing identifier for which amenities changed."
        tests:
          - not_null

      - name: change_at
        description: "Timestamp when the amenities change occurred."
        tests:
          - not_null
      
      - name: change_date
        description: "Derived date from change_at for daily joins."
        tests: 
          - not_null      

      - name: amenities_raw
        description: "Raw JSON-like string of amenities at the time of change."
