version: 2

models:
  - name: dim_listings
    description: "Listing dimension with attributes, latest amenity flags, and review aggregates."
    columns:
      - name: listing_id
        tests: 
        - not_null 
        - unique
      - name: listing_name
      - name: property_type
      - name: room_type
      - name: accommodates
      - name: has_wifi
      - name: has_air_conditioning
      - name: has_kitchen
      - name: amenity_count_latest
      - name: avg_review_score
      - name: reviews_count

  - name: fct_calendar_daily
    description: "Daily listing fact (listing_id × date) combining calendar signals with listing attributes, review aggregates, and amenity flags."
    columns:
      - name: date
        tests: 
          - not_null
      - name: listing_id
          - not_null
      - name: listing_id
      - name: is_reserved
      - name: price
      - name: revenue
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [listing_id, date]
