version: 2

models:
  - name: dim_listings
    description: "Listing dimension with attributes, latest amenity flags, and review aggregates."
    columns:
      - name: listing_id
        tests: 
        - not_null 
        - unique
      - name: listing_name
      - name: property_type
      - name: room_type
      - name: accommodates
      - name: has_wifi
      - name: has_air_conditioning
      - name: has_kitchen
      - name: amenity_count_latest
      - name: avg_review_score
      - name: reviews_count
